// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *AFC → prelim*
 */
export interface AfcDocumentDataPrelimItem {
  /**
   * fight field in *AFC → prelim*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.prelim[].fight
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  fight: prismic.LinkToMediaField;

  /**
   * description field in *AFC → prelim*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.prelim[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AFC → main*
 */
export interface AfcDocumentDataMainItem {
  /**
   * fight field in *AFC → main*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.main[].fight
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  fight: prismic.LinkToMediaField;

  /**
   * description field in *AFC → main*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.main[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

type AfcDocumentDataSlicesSlice = never;

/**
 * Content for AFC documents
 */
interface AfcDocumentData {
  /**
   * cover field in *AFC*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * titre field in *AFC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * text field in *AFC*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;

  /**
   * prelim field in *AFC*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.prelim[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  prelim: prismic.GroupField<Simplify<AfcDocumentDataPrelimItem>>;

  /**
   * main field in *AFC*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.main[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  main: prismic.GroupField<Simplify<AfcDocumentDataMainItem>>;

  /**
   * Slice Zone field in *AFC*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AfcDocumentDataSlicesSlice> /**
   * Meta Description field in *AFC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: afc.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *AFC*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: afc.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *AFC*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: afc.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * AFC document from Prismic
 *
 * - **API ID**: `afc`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AfcDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AfcDocumentData>, "afc", Lang>;

type ContactDocumentDataSlicesSlice = never;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Titre field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * cta field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta: prismic.KeyTextField;

  /**
   * subtitle field in *Contact*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Slice Zone field in *Contact*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ContactDocumentDataSlicesSlice> /**
   * Meta Description field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * titre field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * email field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField;

  /**
   * subtitle field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.subtitle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * address field in *Footer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.address
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  address: prismic.RichTextField;

  /**
   * instagram field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  instagram: prismic.KeyTextField;

  /**
   * facebook field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.facebook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  facebook: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type GalerieDocumentDataSlicesSlice = ArticleSlice;

/**
 * Content for Galerie documents
 */
interface GalerieDocumentData {
  /**
   * title field in *Galerie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galerie.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Galerie*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: galerie.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Galerie*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: galerie.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<GalerieDocumentDataSlicesSlice> /**
   * Meta Description field in *Galerie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: galerie.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Galerie*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: galerie.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Galerie*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: galerie.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Galerie document from Prismic
 *
 * - **API ID**: `galerie`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalerieDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalerieDocumentData>,
    "galerie",
    Lang
  >;

/**
 * Item in *Header → pages*
 */
export interface HeaderDocumentDataPagesItem {
  /**
   * url field in *Header → pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pages[].url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * titre field in *Header → pages*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pages[].titre
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * logo field in *Header*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * pages field in *Header*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.pages[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pages: prismic.GroupField<Simplify<HeaderDocumentDataPagesItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | HistoriqueSlice
  | CarouselSlice
  | JoinUsSlice
  | SponsorsSlice
  | KeysFactsSlice
  | PresentationClubSlice
  | HeroSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Titre field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type InscriptionDocumentDataSlicesSlice = CalendarSlice | AbonnementSlice;

/**
 * Content for Inscription documents
 */
interface InscriptionDocumentData {
  /**
   * Titre field in *Inscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inscription.titre
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titre: prismic.KeyTextField;

  /**
   * texte field in *Inscription*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inscription.texte
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;

  /**
   * cta_text field in *Inscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: inscription.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * cta_url field in *Inscription*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: inscription.cta_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_url: prismic.LinkField;

  /**
   * Slice Zone field in *Inscription*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: inscription.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<InscriptionDocumentDataSlicesSlice> /**
   * Meta Description field in *Inscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: inscription.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Inscription*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: inscription.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Inscription*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: inscription.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Inscription document from Prismic
 *
 * - **API ID**: `inscription`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type InscriptionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<InscriptionDocumentData>,
    "inscription",
    Lang
  >;

type ServicesDocumentDataSlicesSlice = never;

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
  /**
   * title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Services*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * cover field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.cover
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * CTA Text field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.cta_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_link: prismic.KeyTextField;

  /**
   * video field in *Services*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: services.video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * Slice Zone field in *Services*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice> /**
   * Meta Description field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: services.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Services*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: services.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesDocumentData>,
    "services",
    Lang
  >;

export type AllDocumentTypes =
  | AfcDocument
  | ContactDocument
  | FooterDocument
  | GalerieDocument
  | HeaderDocument
  | HomeDocument
  | InscriptionDocument
  | ServicesDocument;

/**
 * Primary content in *Abonnement → Items*
 */
export interface AbonnementSliceDefaultItem {
  /**
   * title field in *Abonnement → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abonnement.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * price field in *Abonnement → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abonnement.items[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * cover field in *Abonnement → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: abonnement.items[].cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * texte field in *Abonnement → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: abonnement.items[].texte
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texte: prismic.RichTextField;
}

/**
 * Default variation for Abonnement Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AbonnementSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<AbonnementSliceDefaultItem>
>;

/**
 * Slice variation for *Abonnement*
 */
type AbonnementSliceVariation = AbonnementSliceDefault;

/**
 * Abonnement Shared Slice
 *
 * - **API ID**: `abonnement`
 * - **Description**: Abonnement
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AbonnementSlice = prismic.SharedSlice<
  "abonnement",
  AbonnementSliceVariation
>;

/**
 * Primary content in *Article → Primary*
 */
export interface ArticleSliceDefaultPrimary {
  /**
   * title field in *Article → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Article → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * content field in *Article → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Article → Items*
 */
export interface ArticleSliceDefaultItem {
  /**
   * media field in *Article → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.items[].media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>;
}

/**
 * Default variation for Article Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ArticleSliceDefaultPrimary>,
  Simplify<ArticleSliceDefaultItem>
>;

/**
 * Slice variation for *Article*
 */
type ArticleSliceVariation = ArticleSliceDefault;

/**
 * Article Shared Slice
 *
 * - **API ID**: `article`
 * - **Description**: Article
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ArticleSlice = prismic.SharedSlice<
  "article",
  ArticleSliceVariation
>;

/**
 * Primary content in *Calendar → Primary*
 */
export interface CalendarSliceDefaultPrimary {
  /**
   * title field in *Calendar → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Calendar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Calendar → Items*
 */
export interface CalendarSliceDefaultItem {
  /**
   * day field in *Calendar → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.items[].day
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  day: prismic.SelectField<
    "Lundi" | "Mardi" | "Mercredi" | "Jeudi" | "Vendredi" | "Samedi"
  >;

  /**
   * time field in *Calendar → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.items[].time
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  time: prismic.SelectField<
    | "10h30"
    | "11h00"
    | "11h30"
    | "12h00"
    | "12h30"
    | "13h00"
    | "13h30"
    | "14h00"
    | "14h30"
    | "15h00"
    | "15h30"
    | "16h00"
    | "16h30"
    | "17h00"
    | "17h30"
    | "18h00"
    | "18h30"
    | "19h00"
  >;

  /**
   * duration field in *Calendar → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.items[].duration
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  duration: prismic.SelectField<"1h00" | "1h30" | "2h00" | "2h30">;

  /**
   * sport field in *Calendar → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: calendar.items[].sport
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sport: prismic.SelectField<
    | "MMA Tout public"
    | "MMA Compétiteurs"
    | "Grappling Tout public"
    | "Grappling Compétiteurs"
    | "JJB Tout public"
    | "JJB Compétiteurs"
    | "Kick-boxing*"
  >;
}

/**
 * Default variation for Calendar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalendarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CalendarSliceDefaultPrimary>,
  Simplify<CalendarSliceDefaultItem>
>;

/**
 * Slice variation for *Calendar*
 */
type CalendarSliceVariation = CalendarSliceDefault;

/**
 * Calendar Shared Slice
 *
 * - **API ID**: `calendar`
 * - **Description**: Calendar
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CalendarSlice = prismic.SharedSlice<
  "calendar",
  CalendarSliceVariation
>;

/**
 * Primary content in *Carousel → Items*
 */
export interface CarouselSliceDefaultItem {
  /**
   * title field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * subtitle field in *Carousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * media field in *Carousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>;

  /**
   * content field in *Carousel → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<CarouselSliceDefaultItem>
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation = CarouselSliceDefault;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Primary content in *Gallery → Primary*
 */
export interface GallerySliceDefaultPrimary {
  /**
   * hauteur field in *Gallery → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primary.hauteur
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  hauteur: prismic.NumberField;

  /**
   * largeur field in *Gallery → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.primary.largeur
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  largeur: prismic.NumberField;
}

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * media field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>;

  /**
   * posX field in *Gallery → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].posx
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  posx: prismic.NumberField;

  /**
   * posY field in *Gallery → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].posy
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  posy: prismic.NumberField;

  /**
   * hauteur field in *Gallery → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].hauteur
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  hauteur: prismic.NumberField;

  /**
   * largeur field in *Gallery → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].largeur
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  largeur: prismic.NumberField;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySliceDefaultPrimary>,
  Simplify<GallerySliceDefaultItem>
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<
  "gallery",
  GallerySliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Hero field in *Hero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.hero
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero: prismic.ImageField<never>;

  /**
   * cta_text field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * cta_url field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.cta_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_url: prismic.KeyTextField;

  /**
   * title field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Text Left field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text_left
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_left: prismic.KeyTextField;

  /**
   * Text Right field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.text_right
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_right: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Historique → Primary*
 */
export interface HistoriqueSliceDefaultPrimary {
  /**
   * cover field in *Historique → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: historique.primary.cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;
}

/**
 * Primary content in *Historique → Items*
 */
export interface HistoriqueSliceDefaultItem {
  /**
   * media field in *Historique → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: historique.items[].media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>;

  /**
   * title field in *Historique → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: historique.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * content field in *Historique → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: historique.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * orientation field in *Historique → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: historique.items[].orientation
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  orientation: prismic.SelectField<"portrait" | "landscape">;
}

/**
 * Default variation for Historique Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistoriqueSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HistoriqueSliceDefaultPrimary>,
  Simplify<HistoriqueSliceDefaultItem>
>;

/**
 * Slice variation for *Historique*
 */
type HistoriqueSliceVariation = HistoriqueSliceDefault;

/**
 * Historique Shared Slice
 *
 * - **API ID**: `historique`
 * - **Description**: Historique
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HistoriqueSlice = prismic.SharedSlice<
  "historique",
  HistoriqueSliceVariation
>;

/**
 * Primary content in *JoinUs → Primary*
 */
export interface JoinUsSliceDefaultPrimary {
  /**
   * cover field in *JoinUs → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.primary.cover
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover: prismic.ImageField<never>;

  /**
   * title field in *JoinUs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * CTA Text field in *JoinUs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *JoinUs → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: join_us.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_link: prismic.KeyTextField;
}

/**
 * Default variation for JoinUs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinUsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<JoinUsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *JoinUs*
 */
type JoinUsSliceVariation = JoinUsSliceDefault;

/**
 * JoinUs Shared Slice
 *
 * - **API ID**: `join_us`
 * - **Description**: JoinUs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type JoinUsSlice = prismic.SharedSlice<"join_us", JoinUsSliceVariation>;

/**
 * Primary content in *KeysFacts → Primary*
 */
export interface KeysFactsSliceDefaultPrimary {
  /**
   * Number 1 field in *KeysFacts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: keys_facts.primary.number_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_1: prismic.KeyTextField;

  /**
   * Text 1 field in *KeysFacts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: keys_facts.primary.text_1
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_1: prismic.KeyTextField;

  /**
   * Number 2 field in *KeysFacts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: keys_facts.primary.number_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_2: prismic.KeyTextField;

  /**
   * Text 2 field in *KeysFacts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: keys_facts.primary.text_2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_2: prismic.KeyTextField;

  /**
   * Number 3 field in *KeysFacts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: keys_facts.primary.number_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number_3: prismic.KeyTextField;

  /**
   * Text 3 field in *KeysFacts → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: keys_facts.primary.text_3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_3: prismic.KeyTextField;
}

/**
 * Default variation for KeysFacts Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type KeysFactsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<KeysFactsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *KeysFacts*
 */
type KeysFactsSliceVariation = KeysFactsSliceDefault;

/**
 * KeysFacts Shared Slice
 *
 * - **API ID**: `keys_facts`
 * - **Description**: KeysFacts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type KeysFactsSlice = prismic.SharedSlice<
  "keys_facts",
  KeysFactsSliceVariation
>;

/**
 * Primary content in *PresentationClub → Primary*
 */
export interface PresentationClubSliceDefaultPrimary {
  /**
   * title field in *PresentationClub → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation_club.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * text field in *PresentationClub → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: presentation_club.primary.text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField;
}

/**
 * Default variation for PresentationClub Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PresentationClubSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PresentationClubSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PresentationClub*
 */
type PresentationClubSliceVariation = PresentationClubSliceDefault;

/**
 * PresentationClub Shared Slice
 *
 * - **API ID**: `presentation_club`
 * - **Description**: PresentationClub
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PresentationClubSlice = prismic.SharedSlice<
  "presentation_club",
  PresentationClubSliceVariation
>;

/**
 * Primary content in *Sponsors → Primary*
 */
export interface SponsorsSliceDefaultPrimary {
  /**
   * Title field in *Sponsors → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * CTA Text field in *Sponsors → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *Sponsors → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_link: prismic.KeyTextField;
}

/**
 * Primary content in *Sponsors → Items*
 */
export interface SponsorsSliceDefaultItem {
  /**
   * Logo field in *Sponsors → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsors.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Sponsors Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SponsorsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SponsorsSliceDefaultPrimary>,
  Simplify<SponsorsSliceDefaultItem>
>;

/**
 * Slice variation for *Sponsors*
 */
type SponsorsSliceVariation = SponsorsSliceDefault;

/**
 * Sponsors Shared Slice
 *
 * - **API ID**: `sponsors`
 * - **Description**: Sponsors
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SponsorsSlice = prismic.SharedSlice<
  "sponsors",
  SponsorsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AfcDocument,
      AfcDocumentData,
      AfcDocumentDataPrelimItem,
      AfcDocumentDataMainItem,
      AfcDocumentDataSlicesSlice,
      ContactDocument,
      ContactDocumentData,
      ContactDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      GalerieDocument,
      GalerieDocumentData,
      GalerieDocumentDataSlicesSlice,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataPagesItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      InscriptionDocument,
      InscriptionDocumentData,
      InscriptionDocumentDataSlicesSlice,
      ServicesDocument,
      ServicesDocumentData,
      ServicesDocumentDataSlicesSlice,
      AllDocumentTypes,
      AbonnementSlice,
      AbonnementSliceDefaultItem,
      AbonnementSliceVariation,
      AbonnementSliceDefault,
      ArticleSlice,
      ArticleSliceDefaultPrimary,
      ArticleSliceDefaultItem,
      ArticleSliceVariation,
      ArticleSliceDefault,
      CalendarSlice,
      CalendarSliceDefaultPrimary,
      CalendarSliceDefaultItem,
      CalendarSliceVariation,
      CalendarSliceDefault,
      CarouselSlice,
      CarouselSliceDefaultItem,
      CarouselSliceVariation,
      CarouselSliceDefault,
      GallerySlice,
      GallerySliceDefaultPrimary,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HistoriqueSlice,
      HistoriqueSliceDefaultPrimary,
      HistoriqueSliceDefaultItem,
      HistoriqueSliceVariation,
      HistoriqueSliceDefault,
      JoinUsSlice,
      JoinUsSliceDefaultPrimary,
      JoinUsSliceVariation,
      JoinUsSliceDefault,
      KeysFactsSlice,
      KeysFactsSliceDefaultPrimary,
      KeysFactsSliceVariation,
      KeysFactsSliceDefault,
      PresentationClubSlice,
      PresentationClubSliceDefaultPrimary,
      PresentationClubSliceVariation,
      PresentationClubSliceDefault,
      SponsorsSlice,
      SponsorsSliceDefaultPrimary,
      SponsorsSliceDefaultItem,
      SponsorsSliceVariation,
      SponsorsSliceDefault,
    };
  }
}
