// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  abonnement: defineAsyncComponent(() => import("./Abonnement/index.vue")),
  document: defineAsyncComponent(() => import("./Document/index.vue")),
  gallery: defineAsyncComponent(() => import("./Gallery/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  keys_facts: defineAsyncComponent(() => import("./KeysFacts/index.vue")),
  presentation_club: defineAsyncComponent(
    () => import("./PresentationClub/index.vue")
  ),
  sponsors: defineAsyncComponent(() => import("./Sponsors/index.vue")),
});
